version: 2
jobs:
  build:
    docker:
      - image: anapsix/alpine-java:8_jdk_unlimited
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache docker
      - run: ./gradlew test
      - run: ./gradlew :celos-ci:docker
      - run: docker tag celos-ci:latest docker.mediamath.com/intelligence/celos-ci:latest
      - run: docker login -u $CELOS_DOCKER_USER -p $CELOS_DOCKER_PASS docker.mediamath.com
      - run: docker push docker.mediamath.com/intelligence/celos-ci:latest
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: master
